src/groups/urls.py
from django.urls import path

from groups.views import GroupUpdateView, GroupCreateView, GroupDeleteView, GroupListView

app_name = 'groups'

urlpatterns = [

    path('', GroupListView.as_view(), name='list'),
    path('new', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),

]

src/lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('accounts/', include('accounts.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/models.py
from django.db import models

# Create your models here.


class Group(models.Model):

    name = models.CharField(max_length=25, null=False)
    faculty = models.CharField(max_length=80, null=False)
    course = models.IntegerField(null=False, default=1)

    headman = models.OneToOneField(
        to='students.Student',
        on_delete=models.SET_NULL,
        null=True,
        related_name='headed_group'
    )

    def __str__(self):
        return f'{self.name}, {self.faculty}, {self.course}'

src/groups/forms.py
import django_filters

from django.forms import ModelForm, ChoiceField

from groups.models import Group

from students.models import Student


class GroupFilter(django_filters.FilterSet):
    class Meta:
        model = Group
        fields = {
            'course': ['gte', 'lte'],
            'name': ['exact', 'startswith', 'icontains'],
            'faculty': ['exact', 'startswith', 'icontains'],
        }


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class GroupCreateForm(GroupBaseForm):
    pass


class GroupUpdateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        exclude = ['headman']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        students = [(st.id, st.full_name()) for st in self.instance.students.all()]
        self.fields['headman_field'] = ChoiceField(
            choices=students,
            initial=self.instance.headman.id
        )

    def save(self, commit=True):
        headman = Student.objects.get(id=self.cleaned_data['headman_field'])
        self.instance.headman = headman
        return super().save(commit)

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

# Create your views here.

from groups.forms import GroupCreateForm, GroupUpdateForm, GroupFilter
from groups.models import Group


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'groups-list.html'
    login_url = reverse_lazy('accounts:login')
    paginate_by = 1
    context_object_name = 'groups'

    def get_filter(self):
        return GroupFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related('headman')
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        return context


class GroupDeleteView(DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    template_name = 'groups-delete.html'
    pk_url_kwarg = "id"


class GroupCreateView(CreateView):
    model = Group
    form_class = GroupCreateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups-create.html'
    pk_url_kwarg = "id"


class GroupUpdateView(UpdateView):

    model = Group
    form_class = GroupUpdateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups-update.html'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.select_related('group', 'headed_group').all()
        context['teachers'] = self.get_object().teachers.select_related('group').all()
        return context

src/groups/templates/groups-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Create group</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Create">
    </form>
{% endblock %}

src/groups/templates/groups-delete.html
{% extends 'base.html' %}


{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Delete group</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      <h3>Do you really want to delete {{group.name}}</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'groups:list'%}" class="btn btn-light">Cancel</a>
    </form>
{% endblock %}

src/groups/templates/groups-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <br><a class="btn btn-secondary" href="{% url 'groups:create' %}" style="font-size: 30px">Create new group</a>
    <h1><font size="60px" color="#ffa600"  face="Calibri">Groups list</font></h1>
{% endblock %}


{% block main %}
    <div class="border p-3 m-3 bg-light text-dark rounded">
        <form method='get'>

          {{filter.form|crispy}}
          <input type="submit" class="btn btn-success" value="Search">
           <a class="btn btn-warning" href="{% url 'groups:list' %}">Reset</a>
        </form>
    </div>

    <table class="table table-striped table-hover">
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Faculty</th>
            <th>Course</th>
            <th>Headman</th>
            <th>✏️</th>
            <th>🗑</th>
          </tr>

    {% for group in groups %}
        <tr>
            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
            <td>{{ group.name }}</td>
            <td>{{ group.faculty }}</td>
            <td>{{ group.course }}</td>
            <td>{{ group.headman }}</td>
            <td><a href="{% url 'groups:update' group.id %}">UPDATE</a></td>
            <td><a href="{% url 'groups:delete' group.id %}">DELETE</a></td>
        </tr>
    {% endfor %}
    </table>

    {% include 'includes/paginator.html' %}

{% endblock %}

src/groups/templates/groups-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Edit group</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input type="submit" class="btn btn-success" value="Update">
    </form>

<h2 style="text-align: center; font-family: Arial"><br>Students:</h2>
    {% include 'includes/students-table.html' %}

<h2 style="text-align: center; font-family: Arial"><br>Teachers:</h2>
    {% include 'includes/teachers-table.html' %}

{% endblock %}