src/accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    UserPasswordChangeView, AccountDeleteView

app_name = 'accounts'

urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', UserPasswordChangeView.as_view(), name='password'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

src/lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('accounts/', include('accounts.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.contrib.auth.models import User
from django.db import models # noqa

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    interests = models.CharField(max_length=128, null=True)

src/accounts/forms.py
from PIL import Image

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from accounts.models import Profile


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'interests']

    def save(self, commit=True):
        super().save(commit)
        image = Image.open(self.instance.image)
        image.thumbnail((300, 300), Image.ANTIALIAS)
        image.save(self.instance.image.path)

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render # noqa
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView, DeleteView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, AccountProfileUpdateForm


# Create your views here.


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully registered')
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'User {self.request.user} successfully logged in')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(self.request, f'User {self.request.user} has been logged out')
        return super().dispatch(request, *args, **kwargs)


class AccountUpdateView(ProcessFormView):
    # model = User
    # template_name = 'profile.html'
    # success_url = reverse_lazy('index')
    # form_class = AccountUpdateForm
    #
    # def get_object(self, queryset=None):
    #     return self.request.user
    #
    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     messages.success(self.request, 'Profile successfully updated')
    #     return result

    def get(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user)
        profile_form = AccountProfileUpdateForm(instance=profile)

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(
            data=request.POST,
            instance=user
        )

        profile_form = AccountProfileUpdateForm(
            data=request.POST,
            files=request.FILES,
            instance=profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(self.request, 'Profile successfully updated')
            return HttpResponseRedirect(reverse('accounts:profile'))

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form
            }
        )


class AccountDeleteView(DeleteView):
    model = User
    template_name = 'delete.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('accounts:profile')
    template_name = 'password-change.html'

src/accounts/templates/delete.html
{% extends 'base.html' %}


{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Delete account</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      <h3>Do you really want to delete account "{{user.username}}"?</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'accounts:profile'%}" class="btn btn-light">Cancel</a>
    </form>
{% endblock %}

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Login as user</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Login">
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
   <div style="text-align: center">
      <a href="{% url 'index' %}"  class="btn btn-info" style="font-size: 25px">Home</a>
   </div>
{% endblock %}


{% block main %}
{% endblock %}

src/accounts/templates/password-change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Change password</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-success" type="submit" value="Change">
    </form>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Account update</font> </h1>
{% endblock %}


{% block main %}
    <div>
        <form method='post' enctype="multipart/form-data">
          {% csrf_token %}

          <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200" alt="default" src="{{ user.profile.image.url }}">
            </div>
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading" style="margin-top: 15px;">USERNAME: {{ user.username }}</h2>
                <h3 class="account-heading">FULL NAME: {{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">EMAIL: {{ user.email }}</p>
            </div>
          </div>

          {{user_form|crispy}}
          {{profile_form|crispy}}

          <input class="btn btn-success" type="submit" value="Save">
          <a href="{% url 'accounts:password' %}" class="btn btn-info">Change password</a>
          <a href="{% url 'accounts:delete' user.id %}" class="btn btn-danger">Delete Account</a>
        </form>
    </div>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Account creation</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Create">
    </form>
{% endblock %}