src/accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    UserPasswordChangeView, AccountDeleteView

app_name = 'accounts'

urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', UserPasswordChangeView.as_view(), name='password'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

src/courses/urls.py
from django.urls import path

from courses.views import CourseDeleteView, CourseUpdateView, CourseCreateView, CourseListView

app_name = 'courses'

urlpatterns = [

    path('', CourseListView.as_view(), name='list'),
    path('new', CourseCreateView.as_view(), name='create'),
    path('edit/<int:id>', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:id>', CourseDeleteView.as_view(), name='delete'),

]

src/groups/urls.py
from django.urls import path

from groups.views import GroupUpdateView, GroupCreateView, GroupDeleteView, GroupListView

app_name = 'groups'

urlpatterns = [

    path('', GroupListView.as_view(), name='list'),
    path('new', GroupCreateView.as_view(), name='create'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),

]

src/lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('accounts/', include('accounts.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from students.views import StudentUpdateView, StudentDeleteView, StudentCreateView, StudentListView

app_name = 'students'

urlpatterns = [

    path('', StudentListView.as_view(), name='list'),
    path('new', StudentCreateView.as_view(), name='create'),
    path('edit/<int:id>', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:id>', StudentDeleteView.as_view(), name='delete'),

]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>LMS</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container">

  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}" style="color: gold; font-size: 60px">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'students:list' %}" style="color: green; font-size: 30px">Students</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'teachers:list' %}" style="color: green; font-size: 30px">Teachers</a>
        </li>

         <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:list' %}" style="color: green; font-size: 30px">Groups</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:list' %}" style="color: green; font-size: 30px">Courses</a>
        </li>

      </ul>

    </div>

       <ul class="navbar-nav">
        {% if user.is_authenticated %}

           <li>
             <a href="{% url 'accounts:profile' %}"><img  src="{{user.profile.image.url}}" width="40px"></a>
           </li>

           <li class="nav-item">
             <a class="nav-link" href="{% url 'accounts:profile' %}" style="color: white; font-size: 20px">Profile ({{user.username}})</a>
            </li>

           <li class="nav-item">
             <a class="nav-link" href="{% url 'accounts:logout' %}" style="color: white; font-size: 20px">Logout</a>
           </li>

        {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:registration' %}" style="color: white; font-size: 20px">Registration</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}" style="color: white; font-size: 20px">Sign in</a>
            </li>

        {% endif %}
       </ul>
  </div>
  </div>
</nav>


<div class="container" >

    {% include 'includes/messages.html' %}

    <div class="border p-3 m-3 rounded bg-light" style="text-align: center">
        {% block operation%}
            <h1>Welcome to LMS</h1>
        {% endblock %}
    </div>

{% block main %}
{% endblock %}

</div>


</body>
</html>

src/templates/index.html
{% extends 'base.html' %}


{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Welcome to LMS!!!</font> </h1>
{% endblock %}