src/courses/urls.py
from django.urls import path

from courses.views import CourseDeleteView, CourseUpdateView, CourseCreateView, CourseListView

app_name = 'courses'

urlpatterns = [

    path('', CourseListView.as_view(), name='list'),
    path('new', CourseCreateView.as_view(), name='create'),
    path('edit/<int:id>', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:id>', CourseDeleteView.as_view(), name='delete'),

]

src/lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('accounts/', include('accounts.urls')),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/models.py
import random

from django.db import models

# Create your models here.


class Course(models.Model):
    class DIFFICULTY(models.IntegerChoices):
        TRIVIAL = 0, "Trivial"
        EASY = 1, "Easy"
        MEDIUM = 2, "Medium"
        EXPERT = 3, "Expert"
        HARDCORE = 4, "Hardcore"

    name = models.CharField(max_length=64, null=False)

    group = models.OneToOneField(
        to='groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        related_name='group_course'
    )

    teachers = models.ManyToManyField(
        to='teachers.Teacher',
        related_name='courses'
    )

    difficulty = models.PositiveSmallIntegerField(
        choices=DIFFICULTY.choices,
        default=DIFFICULTY.MEDIUM
    )

    def __str__(self):
        return f'{self.name}, {self.difficulty}'

    def get_teachers(self):
        return ', '.join(
            teacher.full_name()
            for teacher in self.teachers.all()
        )

    @classmethod
    def generate_course(cls, count):
        courses = ['JavaScript', 'Python', 'PHP', 'C++', 'Java']

        for _ in range(count):
            obj = cls(
                name=random.choice(courses),
                difficulty=random.choice(cls.DIFFICULTY.values)
            )
            obj.save()

src/courses/forms.py
import django_filters

from django.forms import ModelForm

from courses.models import Course


class CourseFilter(django_filters.FilterSet):
    class Meta:
        model = Course
        fields = {
            'name': ['exact', 'icontains']
        }


class CourseBaseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class CourseCreateForm(CourseBaseForm):
    pass


class CourseUpdateForm(CourseBaseForm):
    pass

src/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render # noqa
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
# Create your views here.

from courses.forms import CourseFilter, CourseUpdateForm, CourseCreateForm
from courses.models import Course


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'courses-list.html'
    login_url = reverse_lazy('accounts:login')

    def get_filter(self):
        return CourseFilter(
            data=self.request.GET,
            queryset=self.model.objects.all().select_related('group').prefetch_related('teachers')
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        return context


class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('courses:list')
    template_name = 'courses-delete.html'
    pk_url_kwarg = "id"


class CourseCreateView(CreateView):
    model = Course
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses-create.html'
    pk_url_kwarg = "id"


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseUpdateForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses-update.html'
    pk_url_kwarg = 'id'

src/courses/templates/courses-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Create course</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input class="btn btn-secondary" type="submit" value="Create">
    </form>
{% endblock %}

src/courses/templates/courses-delete.html
{% extends 'base.html' %}


{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Delete course</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      <h3>Do you really want to delete {{course.name}} course</h3>

      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'courses:list'%}" class="btn btn-light">Cancel</a>
    </form>
{% endblock %}

src/courses/templates/courses-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <br><a class="btn btn-secondary" href="{% url 'courses:create' %}" style="font-size: 30px">Create new course</a>
    <h1><font size="60px" color="#ffa600"  face="Calibri">Courses list</font></h1>
{% endblock %}


{% block main %}
    <div class="border p-3 m-3 bg-light text-dark rounded">
        <form method='get'>

          {{filter.form|crispy}}
          <input type="submit" class="btn btn-success" value="Search">
           <a class="btn btn-warning" href="{% url 'courses:list' %}">Reset</a>
        </form>
    </div>

    <table class="table table-striped table-hover">
          <tr>
            <th>Name</th>
            <th>Difficulty</th>
            <th>Group</th>
            <th>Teachers</th>
            <th>✏️</th>
            <th>🗑</th>
          </tr>

    {% for course in filter.qs %}
        <tr>
            <td>{{ course.name }}</td>
            <td>{{ course.difficulty }}</td>
            <td>{{ course.group }}</td>
            <td>{{ course.get_teachers }}</td>
            <td><a href="{% url 'courses:update' course.id %}">UPDATE</a></td>
            <td><a href="{% url 'courses:delete' course.id %}">DELETE</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

src/courses/templates/courses-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block operation%}
    <h1><font size="60px" color="#ffa600"  face="Calibri">Edit course</font> </h1>
{% endblock %}


{% block main %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input type="submit" class="btn btn-success" value="Update">
    </form>
{% endblock %}